### ISSUE TITLE
update go.mod and go.sum to use latest  ec2-instances-info version

### ISSUE THREAD

**Issue by yixuanhu** [cloudutil/AutoSpotting#485]
# Github issue #
We are trying to use the latest c6i instance in our ASG, but autospotting failed to launch c6i spot instance because it does not have the typeinfo

## Issue type ##

- Bug Report

## Build number #

```text
```

## Summary ##

We are trying to use the latest c6i instance in our ASG, but autospotting failed to launch c6i spot instance because it does not have the typeinfo.
It is because the current master does not use the latest build of https://github.com/cristim/ec2-instances-info.

## Expected results ##
able to launch c6i spot instance

## Actual results ##

fail to launch c6i spot instance

```text
```

**Comment by cristim** [comment]
Thanks for reporting this issue.

I currently only work on issues and feature requests submitted by paying customers.

If you installed AutoSpotting from the marketplace tell me your account number on Slack and I'll look into this.

Otherwise I'm going to leave this open just in case someone else is willing to give it a try and  contribute a pull request, which I'm more than happy to consider.

**Comment by cristim** [comment]
I recently updated the instance type information un to including the newly released I4i instance types, let me know if you notice any issues.
